apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "linkace.fullname" . }}-cronjob
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid  # Set these via values
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit | default 2 }}
  {{- if .Values.cronjob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  {{- end }}
  jobTemplate:
    spec:
      {{- if .Values.cronjob.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
      {{- end }}
      {{- if .Values.cronjob.backoffLimit }}
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      {{- end }}
      {{- if .Values.cronjob.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.cronjob.ttlSecondsAfterFinished }}
      {{- end }}
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: {{ .Release.Name }}-app-logs
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-app-logs-pvc
            - name: {{ .Release.Name }}-app-backups
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-app-backups-pvc
          containers:
            - name: {{ .Release.Name }}-cron
              image: "{{ .Values.linkace.repository }}:{{ .Values.linkace.tag }}"
              command: ["php", "artisan", "schedule:run"]
              {{- if .Values.cronjob.resources }}
              resources:
                {{- toYaml .Values.cronjob.resources | nindent 14 }}
              {{- end }}
              envFrom:
                - secretRef:
                    name: {{ default .Release.Name .Values.config.existingSecret }}-env
              volumeMounts:
                - name: {{ .Release.Name }}-app-logs
                  mountPath: "/app/storage/logs"
                - name: {{ .Release.Name }}-app-backups
                  mountPath: "/app/storage/app/backups/LinkAce"
